name: Run Unit Test and Linter On Commit

on:
  push:
jobs:
  run-unit-test:
    name: Run unit test and linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint

      - name: Run unit test
        run: npm test